### ISSUE TITLE
Statusmap error

### ISSUE THREAD

**Issue by sinankizar** [ilovepancakes95/idrac_snmp-grafana#37]
Hello and thank you for the update. I am on grafana 10 and global status panel gives me the error on screenshot:

<img width="836" alt="image" src="https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/28201097/f2cb3ebe-053f-44fc-b43c-2aa434c2bfb5">

Thanks in advance :)

**Comment by ilovepancakes95** [comment]
This is simply a limitation in Grafana I think, as it can only display so many data points on a status map panel before there are too many to factor in to displaying. If you change the time range of the dashboard to something like "Past 1 Hour" it should display correctly.

If you want to customize your setup to still display the status map even when using a time range like "Past 3 Days" you'll need to modify the query frequency to only record a status update point to the database every hour let's say rather than every 30 seconds. Or change the panel to only "read" points from the database every hour rather than using every single point available.

**Comment by sinankizar** [comment]
Thanks for the detiled reply bur i couldn't seem to find how to do those. Can you please point me out?

**Comment by ilovepancakes95** [comment]
You want to edit the panel query and set a "Limit" to be the max number of points the panel is allowed to render. The correct value will depend on the size of your window and the resolution of your monitor actually. The "larger" the panel physically on the screen the more points it can display before the error is shown. See below image of where to set this in the query editor.

<img width="1153" alt="Screenshot 2024-05-24 at 3 37 39 PM" src="https://github.com/ilovepancakes95/idrac_snmp-grafana/assets/52054078/0005783d-f168-46a7-a5c2-98b0d28fd48d">

**Comment by sinankizar** [comment]
hello again,

Sorry for resurrecting this but if it is possible i want to display this in 30min intervals. The panel displays the data with 10 second intervals. Can you please point me out how to aciheve this?

Thanks in advance :)
