### ISSUE TITLE
No CPU Temp on PowerEdge R420

### ISSUE THREAD

**Issue by xyz2610** [ilovepancakes95/idrac_snmp-grafana#5]
I can't seem to get any data for CPU Temperature on my R420 running Firmware Version 2.65.65.65. I only have one CPU installed. I suspect the OID is different for the R420?

**Comment by ilovepancakes95** [comment]
It does seem that for some reason, iDRAC changes the OID numbers to something completely out of order based on configuration, rather than just increasing the last digit of the OID for each component in a group that exists, like multiple CPUs. The easiest way to tell which OID is CPU temp on your system us to run an snmpwalk or use an MIB browser with Dell's MIB files. It will give an indication of which one is "CPU 1 Temp" or maybe on single CPU systems it just says "CPU Temp". All of my test systems are two CPUs.

**Comment by xyz2610** [comment]
I just figured out that `.1.3.6.1.4.1.674.10892.5.4.700.20.1.6.1.2` is CPU 1 Temp for my R420 in single CPU config. That corresponds with "Exhaust temperature" in your idrac-input.conf

**Comment by ilovepancakes95** [comment]
Crazy, I honestly can't think of a reason why it would be designed this way especially between similar systems or such a trivial difference like 1 CPU vs 2 CPUs. Glad you got it.
