### ISSUE TITLE
SNMP oids for temperature graphs in wrong places for R640 series

### ISSUE THREAD

**Issue by mikkoss** [ilovepancakes95/idrac_snmp-grafana#6]
Hi,
Excellent dashboard for dell idrac's. Tested it with our R630 and R640 servers and noticed following problem with temperatures. Different generations have different order for temperature sensors which causes graphs to be with wrong names. 
 
Dell R640
snmpwalk -c public xxx.xxx.com -v2c .1.3.6.1.4.1.674.10892.5.4.700.20.1
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.1 = STRING: "CPU1 Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.2 = STRING: "CPU2 Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.3 = STRING: "System Board Inlet Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.4 = STRING: "System Board Exhaust Temp"

SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.1 = INTEGER: 640
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.2 = INTEGER: 780
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.3 = INTEGER: 200
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.4 = INTEGER: 460

Dell R630
snmpwalk -c public xxx.xxx.com -v2c .1.3.6.1.4.1.674.10892.5.4.700.20.1
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.1 = STRING: "System Board Inlet Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.2 = STRING: "System Board Exhaust Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.3 = STRING: "CPU1 Temp"
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.8.1.4 = STRING: "CPU2 Temp"

SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.1 = INTEGER: 190
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.2 = INTEGER: 390
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.3 = INTEGER: 580
SNMPv2-SMI::enterprises.674.10892.5.4.700.20.1.6.1.4 = INTEGER: 520

It would be nice to get this fixed on the dashboard.

**Comment by ilovepancakes95** [comment]
Although annoying to have to do, rather than it just "working", it is an easy fix, simply by changing the OIDs in the example config file I provided. It's an example file provided based on my test setup. It will need to be customized depending on each person's setup.

I am sure there is a way to create some regex filters or logic that snmp walks everything on each idrac and then finds the strings for each value and dynamically matches it up to the OID for that raw value, however making that logic is something beyond the scope of my knowledge right now. Will make an enhancement issue for this though and maybe somebody else will have the know how to do one day.
